import React, { useState, useEffect } from "react";
import { createPortal } from "react-dom";

export default function NewQuoteModal({ open, onClose, onSubmit, defaultExchangeRate = 0.75 }) {
  const [travelAgency, setTravelAgency] = useState("");
  const [travelAdvisor, setTravelAdvisor] = useState("");
  const [clientName, setClientName] = useState("");
  const [destinations, setDestinations] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [numberOfPax, setNumberOfPax] = useState(2);
  const [exchangeRate, setExchangeRate] = useState(defaultExchangeRate);
  const [hassleTaxPerPax, setHassleTaxPerPax] = useState(150);
  const [internalNote, setInternalNote] = useState("");
  const [internalName, setInternalName] = useState("");

  // Calculate duration when dates change
  useEffect(() => {
    if (startDate && endDate) {
      const start = new Date(startDate);
      const end = new Date(endDate);
      if (end < start) {
        // Auto-adjust end date if before start date
        const newEndDate = new Date(start);
        newEndDate.setDate(newEndDate.getDate() + 1);
        setEndDate(newEndDate.toISOString().slice(0, 10));
      }
    }
  }, [startDate, endDate]);

  // Generate internal name automatically
  useEffect(() => {
    let name = "";
    const parts = [];
    
    if (travelAgency) parts.push(travelAgency);
    if (travelAdvisor) parts.push(travelAdvisor);
    if (destinations) parts.push(destinations);
    
    if (startDate) {
      const date = new Date(startDate);
      const monthNames = ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"];
      const month = monthNames[date.getMonth()];
      const year = date.getFullYear();
      parts.push(`${month} ${year}`);
    }
    
    if (numberOfPax) {
      parts.push(`${numberOfPax}pax`);
    }
    
    name = parts.join(" - ");
    setInternalName(name);
  }, [travelAgency, travelAdvisor, destinations, startDate, numberOfPax]);

  // Update exchange rate when defaultExchangeRate prop changes
  useEffect(() => {
    if (open && defaultExchangeRate) {
      setExchangeRate(defaultExchangeRate);
    }
  }, [defaultExchangeRate, open]);

  // Reset form when modal opens
  useEffect(() => {
    if (open) {
      setTravelAgency("");
      setTravelAdvisor("");
      setClientName("");
      setDestinations("");
      setStartDate("");
      setEndDate("");
      setNumberOfPax(2);
      setExchangeRate(defaultExchangeRate);
      setHassleTaxPerPax(150);
      setInternalNote("");
      setInternalName("");
    }
  }, [open, defaultExchangeRate]);

  // Prevent body scroll when modal is open
  useEffect(() => {
    if (open) {
      const originalStyle = window.getComputedStyle(document.body).overflow;
      document.body.style.overflow = "hidden";
      return () => {
        document.body.style.overflow = originalStyle;
      };
    }
  }, [open]);

  // Handle escape key
  useEffect(() => {
    const onKey = (e) => {
      if (e.key === "Escape") onClose?.();
    };
    if (open) {
      document.addEventListener("keydown", onKey);
      return () => document.removeEventListener("keydown", onKey);
    }
  }, [open, onClose]);

  if (!open) return null;

  const handleSubmit = () => {
    if (!startDate || !endDate) {
      alert("Start date and End date are mandatory");
      return;
    }

    const hassleTotal = hassleTaxPerPax * numberOfPax;

    onSubmit({
      travelAgency,
      travelAdvisor,
      clientName,
      destinations,
      startDate,
      endDate,
      numberOfPax,
      exchangeRate,
      hassleTaxPerPax,
      hassleTotal,
      internalNote,
      internalName: internalName || "New Quote",
    });
  };

  const handleResetInternalName = () => {
    setInternalName("");
    // Will be regenerated by useEffect
  };

  const parseLocaleFloat = (s) => {
    if (s == null) return 0;
    if (typeof s === "number") return s;
    return Number(String(s).trim().replace(/\s/g,"").replace(",", ".")) || 0;
  };

  return createPortal(
    <div
      className="dest-modal-backdrop"
      style={{
        position: "fixed",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 99999,
        background: "rgba(0,0,0,0.30)"
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose?.();
      }}
      role="dialog"
      aria-modal="true"
    >
      <div
        className="modal-card"
        style={{
          minWidth: 600,
          maxWidth: 800,
          position: "relative",
          zIndex: 100000,
          pointerEvents: "auto",
          maxHeight: "90vh",
          overflowY: "auto"
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <h2 className="modal-title">New Quote</h2>

        <div className="dest-modal-body" style={{ padding: "20px" }}>
          {/* Travel Agency and Travel Advisor on same line */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
            <div className="field">
              <label>Travel agency</label>
              <input
                type="text"
                className="input"
                value={travelAgency}
                onChange={(e) => setTravelAgency(e.target.value)}
                placeholder="Enter travel agency name"
              />
            </div>
            <div className="field">
              <label>Travel advisor</label>
              <input
                type="text"
                className="input"
                value={travelAdvisor}
                onChange={(e) => setTravelAdvisor(e.target.value)}
                placeholder="Enter travel advisor name"
              />
            </div>
          </div>

          {/* Client name and Destinations on same line */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
            <div className="field">
              <label>Client name (optional)</label>
              <input
                type="text"
                className="input"
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                placeholder="Client name"
              />
            </div>
            <div className="field">
              <label>Destination(s)</label>
              <input
                type="text"
                className="input"
                value={destinations}
                onChange={(e) => setDestinations(e.target.value)}
                placeholder="Enter destinations"
              />
            </div>
          </div>

          {/* Start date and End date on same line */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
            <div className="field">
              <label>Start date <span style={{ color: "#f88" }}>*</span></label>
              <input
                type="date"
                className="input"
                value={startDate}
                onChange={(e) => {
                  setStartDate(e.target.value);
                  // Auto-calculate end date if not set
                  if (!endDate && e.target.value) {
                    const start = new Date(e.target.value);
                    start.setDate(start.getDate() + 1);
                    setEndDate(start.toISOString().slice(0, 10));
                  }
                }}
                required
                style={{ 
                  colorScheme: "light",
                  backgroundColor: "#fff",
                  color: "#000"
                }}
              />
            </div>
            <div className="field">
              <label>End date <span style={{ color: "#f88" }}>*</span></label>
              <input
                type="date"
                className="input"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                min={startDate || undefined}
                required
                style={{ 
                  colorScheme: "light",
                  backgroundColor: "#fff",
                  color: "#000"
                }}
              />
              {startDate && endDate && (
                <div style={{ fontSize: 12, opacity: 0.7, marginTop: 4 }}>
                  Duration: {Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24))} day(s)
                </div>
              )}
            </div>
          </div>

          {/* Number of pax */}
          <div className="field">
            <label>Number of pax</label>
            <input
              type="number"
              className="input"
              value={numberOfPax}
              onChange={(e) => setNumberOfPax(Math.max(1, parseInt(e.target.value) || 2))}
              min="1"
            />
          </div>

          {/* Exchange rate and Hassle tax per pax on same line */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
            <div className="field">
              <label>Exchange rate (USD → EUR)</label>
              <input
                type="number"
                step="0.0001"
                className="input"
                value={exchangeRate}
                onChange={(e) => setExchangeRate(parseLocaleFloat(e.target.value) || defaultExchangeRate)}
                placeholder={String(defaultExchangeRate)}
              />
              <div style={{ fontSize: 12, opacity: 0.7, marginTop: 4 }}>
                Default from system: {defaultExchangeRate}
              </div>
            </div>
            <div className="field">
              <label>Hassle tax per pax</label>
              <input
                type="number"
                step="0.01"
                className="input"
                value={hassleTaxPerPax}
                onChange={(e) => setHassleTaxPerPax(parseFloat(e.target.value) || 150)}
              />
            </div>
          </div>

          {/* Internal note */}
          <div className="field">
            <label>Internal note</label>
            <textarea
              className="textarea"
              value={internalNote}
              onChange={(e) => setInternalNote(e.target.value)}
              placeholder="Internal notes"
              rows={4}
            />
          </div>

          {/* Internal name (auto-generated, editable) */}
          <div className="field">
            <label>Internal quote name</label>
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <input
                type="text"
                className="input"
                value={internalName}
                onChange={(e) => setInternalName(e.target.value)}
                placeholder="Auto-generated name"
                style={{ flex: 1 }}
              />
              <button
                className="btn ghost"
                onClick={handleResetInternalName}
                type="button"
                style={{ whiteSpace: "nowrap" }}
              >
                Reset
              </button>
            </div>
            <div style={{ fontSize: 12, opacity: 0.7, marginTop: 4 }}>
              Format: (Agency) - (Advisor) - (Destination) - (Month Year) - (Pax)
            </div>
          </div>
        </div>

        <div className="modal-actions" style={{ display: "flex", justifyContent: "flex-end", gap: 8, padding: "16px 20px", borderTop: "1px solid rgba(255,255,255,0.1)" }}>
          <button className="btn ghost" onClick={onClose}>
            Cancel
          </button>
          <button className="btn primary" onClick={handleSubmit} disabled={!startDate || !endDate}>
            Create Quote
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}

