"""add_user_and_login_token_tables

Revision ID: 69b9b9828eee
Revises: 206782af2af6
Create Date: 2025-11-14 10:37:49.808014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '69b9b9828eee'
down_revision: Union[str, Sequence[str], None] = '206782af2af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_expires_at'), 'login_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_tokens_id'), 'login_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_login_tokens_token_hash'), 'login_tokens', ['token_hash'], unique=True)
    op.create_index('ix_login_tokens_user_created', 'login_tokens', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_login_tokens_user_id'), 'login_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_login_tokens_user_id'), table_name='login_tokens')
    op.drop_index('ix_login_tokens_user_created', table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_token_hash'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_id'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_expires_at'), table_name='login_tokens')
    op.drop_table('login_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
