"""Add itinerary_events table

Revision ID: 6c413360c810
Revises: 8df1afd8de02
Create Date: 2025-11-06 16:01:21.537491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c413360c810'
down_revision: Union[str, Sequence[str], None] = '8df1afd8de02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_code', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('service_title', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ef_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_events_category'), 'itinerary_events', ['category'], unique=False)
    op.create_index(op.f('ix_itinerary_events_date'), 'itinerary_events', ['date'], unique=False)
    op.create_index(op.f('ix_itinerary_events_departure_code'), 'itinerary_events', ['departure_code'], unique=False)
    op.create_index(op.f('ix_itinerary_events_service_id'), 'itinerary_events', ['service_id'], unique=False)
    op.create_index(op.f('ix_itinerary_events_service_title'), 'itinerary_events', ['service_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_events_service_title'), table_name='itinerary_events')
    op.drop_index(op.f('ix_itinerary_events_service_id'), table_name='itinerary_events')
    op.drop_index(op.f('ix_itinerary_events_departure_code'), table_name='itinerary_events')
    op.drop_index(op.f('ix_itinerary_events_date'), table_name='itinerary_events')
    op.drop_index(op.f('ix_itinerary_events_category'), table_name='itinerary_events')
    op.drop_table('itinerary_events')
    # ### end Alembic commands ###
