"""Add stg_itinerary_events table

Revision ID: 8df1afd8de02
Revises: f9496fcacb84
Create Date: 2025-11-06 15:58:52.096497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df1afd8de02'
down_revision: Union[str, Sequence[str], None] = 'f9496fcacb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stg_itinerary_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_code', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('service_title', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ef_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('_source_file', sa.String(), nullable=True),
    sa.Column('_source_sheet', sa.String(), nullable=True),
    sa.Column('_row_hash', sa.String(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_itinerary_events__row_hash'), 'stg_itinerary_events', ['_row_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stg_itinerary_events__row_hash'), table_name='stg_itinerary_events')
    op.drop_table('stg_itinerary_events')
    # ### end Alembic commands ###
