"""Initial migration

Revision ID: 9be4229d8ba2
Revises: 
Create Date: 2025-11-06 14:30:10.178671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be4229d8ba2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stg_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('cost_category', sa.String(), nullable=False),
    sa.Column('start_destination', sa.String(), nullable=False),
    sa.Column('hotel_stars', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('image_url_primary', sa.String(), nullable=True),
    sa.Column('image_url_fallback', sa.String(), nullable=True),
    sa.Column('_source_file', sa.String(), nullable=True),
    sa.Column('_source_sheet', sa.String(), nullable=True),
    sa.Column('_row_hash', sa.String(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_services__row_hash'), 'stg_services', ['_row_hash'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('start_destination', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('pax_count', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hotel_stars', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_catalog_category'), 'service_catalog', ['category'], unique=False)
    op.create_index(op.f('ix_service_catalog_company'), 'service_catalog', ['company'], unique=False)
    op.create_index(op.f('ix_service_catalog_name'), 'service_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_service_catalog_start_destination'), 'service_catalog', ['start_destination'], unique=False)
    op.create_table('service_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_images_service_id'), 'service_images', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_images_url'), 'service_images', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_images_url'), table_name='service_images')
    op.drop_index(op.f('ix_service_images_service_id'), table_name='service_images')
    op.drop_table('service_images')
    op.drop_index(op.f('ix_service_catalog_start_destination'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_name'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_company'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_category'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_stg_services__row_hash'), table_name='stg_services')
    op.drop_table('stg_services')
    # ### end Alembic commands ###
