"""cost fields on quotes and lines

Revision ID: d85d0ee84c91
Revises: 727ecce51389
Create Date: 2025-11-06 19:22:16.457540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85d0ee84c91'
down_revision: Union[str, Sequence[str], None] = '727ecce51389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite-compatible migration: skip ALTER COLUMN for NULL constraints
    # SQLite doesn't support ALTER COLUMN to change NULL constraints
    op.create_index(op.f('ix_quote_days_quote_id'), 'quote_days', ['quote_id'], unique=False)
    op.drop_column('quote_days', 'created_at')
    op.drop_column('quote_days', 'updated_at')
    op.add_column('quote_lines', sa.Column('achat_eur', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('achat_usd', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('vente_usd', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('fx_rate', sa.Numeric(precision=14, scale=6), nullable=True))
    # Skip ALTER COLUMN for position and title (SQLite limitation)
    # Skip ALTER COLUMN for base_net_amount precision change (SQLite limitation)
    op.create_index(op.f('ix_quote_lines_quote_day_id'), 'quote_lines', ['quote_day_id'], unique=False)
    op.drop_column('quote_lines', 'created_at')
    op.drop_column('quote_lines', 'updated_at')
    # Add columns with default values for SQLite
    op.add_column('quotes', sa.Column('margin_pct', sa.Numeric(precision=14, scale=6), nullable=False, server_default='0.1627'))
    op.add_column('quotes', sa.Column('onspot_manual', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('hassle_manual', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('onspot_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotes', sa.Column('hassle_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotes', sa.Column('commissionable_net', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotes', sa.Column('commission_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotes', sa.Column('sell_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotes', sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_column('quotes', 'grand_total')
    op.drop_column('quotes', 'sell_total')
    op.drop_column('quotes', 'commission_total')
    op.drop_column('quotes', 'commissionable_net')
    op.drop_column('quotes', 'hassle_total')
    op.drop_column('quotes', 'onspot_total')
    op.drop_column('quotes', 'hassle_manual')
    op.drop_column('quotes', 'onspot_manual')
    op.drop_column('quotes', 'margin_pct')
    op.add_column('quote_lines', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('quote_lines', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_quote_lines_quote_day_id'), table_name='quote_lines')
    op.alter_column('quote_lines', 'base_net_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('quote_lines', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quote_lines', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quote_lines', 'fx_rate')
    op.drop_column('quote_lines', 'vente_usd')
    op.drop_column('quote_lines', 'achat_usd')
    op.drop_column('quote_lines', 'achat_eur')
    op.add_column('quote_days', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('quote_days', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_quote_days_quote_id'), table_name='quote_days')
    op.alter_column('quote_days', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
