"""Add stg_images table

Revision ID: f9496fcacb84
Revises: 9be4229d8ba2
Create Date: 2025-11-06 15:35:09.481389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9496fcacb84'
down_revision: Union[str, Sequence[str], None] = '9be4229d8ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stg_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('start_destination', sa.String(), nullable=True),
    sa.Column('ef_code', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('_source_file', sa.String(), nullable=True),
    sa.Column('_source_sheet', sa.String(), nullable=True),
    sa.Column('_row_hash', sa.String(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_images__row_hash'), 'stg_images', ['_row_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stg_images__row_hash'), table_name='stg_images')
    op.drop_table('stg_images')
    # ### end Alembic commands ###
