"""Add service_popularity table

Revision ID: fe58fce715ac
Revises: 6c413360c810
Create Date: 2025-11-06 16:02:54.382202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe58fce715ac'
down_revision: Union[str, Sequence[str], None] = '6c413360c810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_popularity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('count_365d', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.Column('distinct_departures', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_popularity_service_id'), 'service_popularity', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_popularity_service_id'), table_name='service_popularity')
    op.drop_table('service_popularity')
    # ### end Alembic commands ###
